version: '24.0.7'
services:
  redis:
    image: redis/redis-stack-server:latest
    container_name: redis
    ports:
      - "6379:6379"
    
  backend:
    image: v1n1ts0010411/backend:v6
    container_name: backend
    depends_on:
      - redis
    ports: 
      - "3000:3000"
    
